// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     ExampleRequest.avsc
 *     ExampleResponse.avsc
 */

package record

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ExampleRequest struct {
	JobId   string
	Tag     string
	Configs []string
}

func NewExampleRequestWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &ExampleRequest{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeExampleRequest(r io.Reader) (*ExampleRequest, error) {
	t := NewExampleRequest()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewExampleRequest() *ExampleRequest {
	return &ExampleRequest{}
}

func (r *ExampleRequest) Schema() string {
	return "{\"fields\":[{\"name\":\"JobId\",\"type\":\"string\"},{\"name\":\"Tag\",\"type\":\"string\"},{\"name\":\"configs\",\"type\":{\"items\":\"string\",\"type\":\"array\"}}],\"name\":\"ExampleRequest\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *ExampleRequest) SchemaName() string {
	return "com.pharbers.kafka.schema.ExampleRequest"
}

func (r *ExampleRequest) Serialize(w io.Writer) error {
	return writeExampleRequest(r, w)
}

func (_ *ExampleRequest) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *ExampleRequest) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *ExampleRequest) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *ExampleRequest) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *ExampleRequest) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *ExampleRequest) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *ExampleRequest) SetString(v string)   { panic("Unsupported operation") }
func (_ *ExampleRequest) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *ExampleRequest) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.Tag)
	case 2:
		r.Configs = make([]string, 0)
		return (*ArrayStringWrapper)(&r.Configs)

	}
	panic("Unknown field index")
}
func (r *ExampleRequest) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *ExampleRequest) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ExampleRequest) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *ExampleRequest) Finalize()                        {}

type ExampleRequestReader struct {
	r io.Reader
	p *vm.Program
}

func NewExampleRequestReader(r io.Reader) (*ExampleRequestReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewExampleRequest()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ExampleRequestReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *ExampleRequestReader) Read() (*ExampleRequest, error) {
	t := NewExampleRequest()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
