// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     Es.avsc
 *     ExampleRequest.avsc
 *     ExampleResponse.avsc
 *     HiveTask.avsc
 *     HiveTracebackTask.avsc
 *     MapExample.avsc
 *     OssTask.avsc
 */

package record

import (
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func writeArrayString(r []string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeEs(r *Es, w io.Writer) error {
	var err error
	err = writeString(r.Time, w)
	if err != nil {
		return err
	}
	err = writeString(r.Hostname, w)
	if err != nil {
		return err
	}
	err = writeString(r.Ip, w)
	if err != nil {
		return err
	}
	err = writeString(r.Cpu, w)
	if err != nil {
		return err
	}
	err = writeString(r.Memory, w)
	if err != nil {
		return err
	}
	err = writeString(r.Disk, w)
	if err != nil {
		return err
	}
	err = writeString(r.Receive, w)
	if err != nil {
		return err
	}
	err = writeString(r.Transmit, w)
	if err != nil {
		return err
	}

	return nil
}
func writeExampleRequest(r *ExampleRequest, w io.Writer) error {
	var err error
	err = writeString(r.JobId, w)
	if err != nil {
		return err
	}
	err = writeString(r.Tag, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Configs, w)
	if err != nil {
		return err
	}

	return nil
}
func writeExampleResponse(r *ExampleResponse, w io.Writer) error {
	var err error
	err = writeString(r.JobId, w)
	if err != nil {
		return err
	}
	err = writeLong(r.Progress, w)
	if err != nil {
		return err
	}
	err = writeString(r.Error, w)
	if err != nil {
		return err
	}

	return nil
}
func writeHiveTask(r *HiveTask, w io.Writer) error {
	var err error
	err = writeString(r.JobId, w)
	if err != nil {
		return err
	}
	err = writeString(r.TraceId, w)
	if err != nil {
		return err
	}
	err = writeString(r.DatasetId, w)
	if err != nil {
		return err
	}
	err = writeString(r.Url, w)
	if err != nil {
		return err
	}
	err = writeInt(r.Length, w)
	if err != nil {
		return err
	}
	err = writeString(r.TaskType, w)
	if err != nil {
		return err
	}
	err = writeString(r.Remarks, w)
	if err != nil {
		return err
	}

	return nil
}
func writeHiveTracebackTask(r *HiveTracebackTask, w io.Writer) error {
	var err error
	err = writeString(r.JobId, w)
	if err != nil {
		return err
	}
	err = writeString(r.TraceId, w)
	if err != nil {
		return err
	}
	err = writeString(r.DatasetId, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.ParentDatasetId, w)
	if err != nil {
		return err
	}
	err = writeParentUrlRecord(r.ParentUrl, w)
	if err != nil {
		return err
	}
	err = writeInt(r.Length, w)
	if err != nil {
		return err
	}
	err = writeString(r.TaskType, w)
	if err != nil {
		return err
	}
	err = writeString(r.Remarks, w)
	if err != nil {
		return err
	}

	return nil
}

func writeInt(r int32, w io.Writer) error {
	downShift := uint32(31)
	encoded := uint64((uint32(r) << 1) ^ uint32(r>>downShift))
	const maxByteSize = 5
	return encodeInt(w, maxByteSize, encoded)
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeMapExample(r *MapExample, w io.Writer) error {
	var err error
	err = writeMapString(r.TestMap, w)
	if err != nil {
		return err
	}

	return nil
}

func writeMapString(r *MapString, w io.Writer) error {
	err := writeLong(int64(len(r.M)), w)
	if err != nil || len(r.M) == 0 {
		return err
	}
	for k, e := range r.M {
		err = writeString(k, w)
		if err != nil {
			return err
		}
		err = writeString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeOssTask(r *OssTask, w io.Writer) error {
	var err error
	err = writeString(r.AssetId, w)
	if err != nil {
		return err
	}
	err = writeString(r.JobId, w)
	if err != nil {
		return err
	}
	err = writeString(r.TraceId, w)
	if err != nil {
		return err
	}
	err = writeString(r.OssKey, w)
	if err != nil {
		return err
	}
	err = writeString(r.FileType, w)
	if err != nil {
		return err
	}
	err = writeString(r.FileName, w)
	if err != nil {
		return err
	}
	err = writeString(r.SheetName, w)
	if err != nil {
		return err
	}
	err = writeString(r.Owner, w)
	if err != nil {
		return err
	}
	err = writeLong(r.CreateTime, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Labels, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.DataCover, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.GeoCover, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Markets, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Molecules, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Providers, w)
	if err != nil {
		return err
	}

	return nil
}
func writeParentUrlRecord(r *ParentUrlRecord, w io.Writer) error {
	var err error
	err = writeString(r.MetaData, w)
	if err != nil {
		return err
	}
	err = writeString(r.SampleData, w)
	if err != nil {
		return err
	}

	return nil
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}

type ArrayStringWrapper []string

func (_ *ArrayStringWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) Finalize()                        {}
func (_ *ArrayStringWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayStringWrapper) AppendArray() types.Field {
	var v string

	*r = append(*r, v)
	return (*types.String)(&(*r)[len(*r)-1])
}

type MapString struct {
	keys   []string
	values []string
	M      map[string]string
}

func NewMapString() *MapString {
	return &MapString{
		keys:   make([]string, 0),
		values: make([]string, 0),
		M:      make(map[string]string),
	}
}

func (_ *MapString) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapString) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapString) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapString) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapString) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapString) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapString) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapString) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapString) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapString) SetDefault(i int)      { panic("Unsupported operation") }
func (r *MapString) Finalize() {
	for i := range r.keys {
		r.M[r.keys[i]] = r.values[i]
	}
	r.keys = nil
	r.values = nil
}

func (r *MapString) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v string

	r.values = append(r.values, v)
	return (*types.String)(&r.values[len(r.values)-1])
}

func (_ *MapString) AppendArray() types.Field { panic("Unsupported operation") }
